management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: beans
spring:
  data:
    rest:
      base-path: /api-autogeneree/
      detection-strategy: annotated
  datasource:
    url: jdbc:h2:mem:plage
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.format-sql: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp