logging:
  level:
    '[org.springframework': WARN
    root: WARN
  file:
    name: log/plage_log
management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      base-path: /
      exposure:
        include: beans
spring:
  data:
    rest:
      base-path: /api-autogeneree/
      detection-strategy: annotated
  datasource:
    url: jdbc:h2:mem:plage
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
requete-clients-par-code-pays: FROM Client WHERE pays.code=:code 